# Generated by Django 5.1.3 on 2025-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMP', 'Employer'), ('CAN', 'Candidate')], max_length=3),
        ),
    ]
